# run the pipeline on changes in the master branch
trigger:
  - master

# build environment - OS
pool:
  vmImage: 'windows-latest' # Change to windows-latest

steps:
  # build environment - Node
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x' # Use the desired Node.js version
    displayName: 'install node.js'

  # NPM task
  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  # Git task
  - script: |
      # remove git history and settings - to avoid inheritance
      rm -rf .git
      # re-initialise git
      git init
      git config user.name "OffBeatPixels" # Replace <yourName> with your GitHub username
      git config user.email "offbeatpixels@gmail.com" # Replace <yourEmail> with your GitHub email
      git remote set-url origin https://OffBeatPixels:${GIT_TOKEN}@github.com/OffBeatPixels/MGF.git # Fill in <githubLogin> and <publicRepositoryName>
      # add and commit /docs/ folder
      git add docs
      git commit -m "deploy the bundle"
      # push the commit to the public repository
      git push origin HEAD:master --force
    displayName: 'deploy the production bundle'
